### ISSUE TITLE
End-Bildschirm erstellen

### ISSUE THREAD

**Issue by dspeckmann** [SWEProjekt/Freestyler-App#21]
Activity, die nach Beenden der Aufnahme aufgerufen wird. Soll die Dauer der Aufnahme und die verwendeten Wörter anzeigen sowie die Möglichkeiten enthalten, sich den Rap anzuhören, ihn hochzuladen und ins Hauptmenü zu wechseln (3 Buttons).

**Comment by ScarlettMueller** [comment]
Ich denke, dass nicht die verwendeten Wörter angezeigt werden sollten, da so eine Liste schnell den Rahmen sprengt. Spätestens bei über 5 Wörtern, wird das ganze unübersichtlich und ist nicht mehr nutzerfreundlich.

**Comment by dspeckmann** [comment]
Wenn man aber gar keinen Bezug mehr auf die Wörter hat, bringt das ganze Konzept gar nichts. Dann kann man auch einfach so rappen, würde ich sagen. Man könnte die Wörter ja sehr klein anzeigen, vielleicht als eine Art Wolke oder mit Scrollbalken. Ich denke auch nicht, dass da regelmäßig 10 Wörter oder so stehen werden.

**Comment by Projektleitung** [comment]
Man könnte auch  auf einen Button verweisen "Nicht verwendet". Dann würde eine Liste erscheinen wenn man draufdrückt.

**Comment by ScarlettMueller** [comment]
Soll jetzt eine extra Activity für die Wortliste erstellt werden oder sollen die Wörter nicht angezeigt werden?

**Comment by dspeckmann** [comment]
Nicht unbedingt. Wenn ihr sagt, dass das nicht gut aussieht oder sich nicht gut in die App einfügt, lasst es gerne weg :)
