### ISSUE TITLE
Hauptmenü-Bildschirm

### ISSUE THREAD

**Issue by dspeckmann** [SWEProjekt/Freestyler-App#4]
Eine Activity, die beim Start der App aufgerufen wird. Sie soll den Titel der App enthalten sowie einen Button, der den Benutzer zur "Spiel"-Activity bringt.

**Comment by Jespersoe** [comment]
Heute wurden die ersten Skizzen erstellt und ausgearbeitet. 
Diese werden zu Morgen von Julian Henke noch ausgebessert und präsentierbar gemacht.
