### ISSUE TITLE
Wort-Bildschirm erstellen

### ISSUE THREAD

**Issue by dspeckmann** [SWEProjekt/Freestyler-App#41]
Ein Bildschirm, der eine Liste aller Wort-Pakete enthält. Der User kann auswählen, welche er im Spiel haben will (entweder permanent oder für das aktuelle Spiel - Designfrage). Die Daten kommen aus der Datenbank und werden auch dort gespeichert, Funktionen dafür werden vom Backend-Team in Issue #32 entwickelt.

**Comment by ScarlettMueller** [comment]
Soll diese Activity vom Hauptmenü aus erreichbar sein? Oder gehört sie zum Gameflow: Hauptmenü -> Click on Button "Rap" --> Auswahl des Wortpakets --> Beginn des Raps?

**Comment by dspeckmann** [comment]
Wir hatten gedacht, dass es ein extra Bildschirm ist, damit man nicht bei jedem neuen Spiel die Wörter neu ausschen muss. Aber wenn euch auffällt, dass es auf die andere Weise besser ist, macht es so ;)

**Comment by ScarlettMueller** [comment]
Das beantwortet leider nicht meine Frage. Ich weiß, dass es eine eigene Activity sein soll. Die Frage war, ob diese Activty seperat vom Hauptmenü aus erreichbar sein soll, also ob dafüt ein extra Button im Hauptmenü hinzugefügt werden soll so, dass wir dann vier Buttons im Hauptmenü haben (Rap, Feedback, Liste der Raps und Wortpakete).  Oder soll das direkt vor dem Rap aufgerufen werden?

Noch eine weitere Frage: Soll nur ein Wortpaket ausgewählt werden können oder mehrere?

**Comment by dspeckmann** [comment]
Vom Hauptmenü aus erreichbar, ja. Und mehrere.
