### ISSUE TITLE
Spiel-Bildschirm

### ISSUE THREAD

**Issue by dspeckmann** [SWEProjekt/Freestyler-App#5]
Eine Activity, die folgendes enthält:
- Textbox, in der Stichwörter angezeigt werden können
- Button, der das Spiel (Stichwörter-Generierung, Beat-Wiedergabe, Audioaufnahme) startet und stoppt
- Button, der eine vorhandene Aufnahme abspielt
- Button, der zurück zur Hauptmenü-Activity führt
- Button, der Feedback-Activity öffnet

**Comment by Jespersoe** [comment]
Heute wurden die ersten Skizzen erstellt und ausgearbeitet. 
Diese werden zu Morgen von Julian Henke noch ausgebessert und präsentierbar gemacht.
